apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-conv
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: conv.test
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service-conv-app
            port: 
              number: 81
