apiVersion: v1
kind: Service
metadata:
  name: conv-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    components: conv-app
---
apiVersion: v1
kind: Service
metadata:
  name: conv-rmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      protocol: TCP
  selector:
    components: conv-rmq
