apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Values.api.name }}
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHNlcnZpY2Utc2hvcnQtcG9zdGdyZXM6NTQzMi9wb3N0Z3Jlcw==