apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.port }}
      protocol: TCP
  selector:
    components: {{ .Values.app.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.postgres.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      protocol: TCP
  selector:
    components: {{ .Values.postgres.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.api.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      protocol: TCP
  selector:
    components: {{ .Values.api.name }}